name: link_os_multiplatform_sdk
description: "A Flutter plugin that enables cross-platform discovery, connection, and printing with Zebra Link-OS printers using Zebraâ€™s official Link-OS Multiplatform SDK."
version: 0.0.1
homepage: https://github.com/aarajput/link_os_multiplatform_sdk
repository: https://github.com/aarajput/link_os_multiplatform_sdk
issue_tracker: https://github.com/aarajput/link_os_multiplatform_sdk/issues

environment:
  sdk: ^3.10.7
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.1.5

flutter:
  plugin:
    platforms:
      android:
        package: com.wisecrab.link_os_multiplatform_sdk
        pluginClass: LinkOsMultiplatformSdkPlugin
      ios:
        pluginClass: LinkOsMultiplatformSdkPlugin

scripts: derry.yaml
